.travis.yml, LICENSE.md, REQUIRE, appveyor.yml, src/TimeseriesCausality.jl, src/systems/Systems.jl, src/systems/discretemaps/logistic3.jl, test/runtests.jl
=> Example system: three coupled logistic maps with dynamical noise

src/systems/Systems.jl, src/systems/discretemaps/var1.jl, test/runtests.jl
3d system where X1 -> X2 -> X3
=> Implemented autoregressive var1 process

src/systems/Systems.jl, src/systems/continuous_systems/rosslerrossler.jl, src/systems/discretemaps/anishchenko1.jl, test/runtests.jl
Implemented one of the maps from Anischenko et al. (for issue #12).
=> Example system: strange, nonchaotic map (Anischenko 1)

src/systems/Systems.jl, src/systems/continuous_systems/chuacircuits_driven.jl, test/runtests.jl
One 3D Chua circuit forced by a sine function bidirectionally coupled to another 3D Chua circuit forced by a sine function. The subsystems are mutually coupled by a linear
resistor.
=> Implemented 6D  coupled Chua circuit system

src/systems/Systems.jl, src/systems/continuous_systems/lorenztriple.jl, test/runtests.jl
The system has unidirectional forcing X1 -> X2 and X2 -> X3.
=> Implemented 9D triple 3D Lorenz system

src/systems/Systems.jl, src/systems/discretemaps/logistic4.jl, test/runtests.jl
This example is from Ye et al. and is an example of a causal chain where Y1 -> Y2 -> Y3 -> Y4. It was used to demonstrate lagged CCM.
=> Implemented 4D transitive logistic map

REQUIRE
Add missing requirement in REQUIRE
=> Require Reexport

docs/make.jl, docs/src/CHANGELOG.md, docs/src/index.md
- Fix broken links on introduction page in documentation.
=> Release 0.9.4

Project.toml, docs/mkdocs.yml, docs/src/CHANGELOG.md, docs/src/causalitytests/NormalisedPredictiveAsymmetryTest.md, docs/src/causalitytests/PredictiveAsymmetryTest.md, docs/src/causalitytests/SMeasureTest.md, docs/src/causalitytests/causality_from_uncertain_data.md, docs/src/causalitytests/causality_from_uncertain_data_InterpolateBinTest.md, docs/src/causalitytests/causality_from_uncertain_data_RandomSequencesTest.md, docs/src/causalitytests/causality_from_uncertain_data_binneddatacausalitytest.md, docs/src/causalitytests/causality_from_uncertain_data_naive.md, docs/src/causalitytests/causality_from_uncertain_data_naive_constrained.md, docs/src/causalitytests/causality_from_uncertain_data_strictlyincreasing_interpolated.md, docs/src/example_systems/example_systems_discrete.md, docs/src/tutorials/causality/Tutorial_BinnedResampling_RandomSequencesTest_PredictiveAsymmetryTest_ar1_unidir.md, docs/src/tutorials/causality/tutorial_SMeasureTest.md, docs/src/worked_examples/worked_example_transferentropy.md, src/causalitytests/causality_on_uncertaindata.jl, src/causalitytests/highlevel_tests/BinnedDataCausalityTest.jl, src/causalitytests/highlevel_tests/causality_BinnedDataCausalityTest.jl, src/causalitytests/highlevel_tests/causality_InterpolateBinTest.jl, src/causalitytests/highlevel_tests/causality_RandomSequencesTest.jl, src/causalitytests/tests_entropy_based/NearestNeighbourMITest.jl, src/causalitytests/tests_predictive_asymmetry/NormalisedPredictiveAsymmetryTest.jl, src/integration_uncertaindata/integration_with_uncertaindata_constrained_resampling.jl, src/systems/discretemaps/ar1.jl, src/systems/discretemaps/logistic2_unidir.jl, src/systems/discretemaps/logistic4.jl
=> Release 0.9.7

Project.toml, docs/src/CHANGELOG.md, src/causalitytests/highlevel_tests/RandomSequencesTest.jl
- Fixed bug in documentation example for `RandomSequencesTest`
=> Release 0.9.9

src/example_systems/continuous_systems/lorenz_lorenz_lorenz_transitive.jl, src/example_systems/continuous_systems/rosslerrossler.jl, src/example_systems/discretemaps/ar1.jl, src/example_systems/discretemaps/ar1_bidir.jl, src/example_systems/discretemaps/henontriple.jl, src/example_systems/discretemaps/nonlinear3D_linear_and_nonlinear_coupling.jl, src/example_systems/discretemaps/nontrivial_pegiun.jl, src/example_systems/discretemaps/ulammap.jl, src/example_systems/discretemaps/var1.jl
=> Changed name of initial conditions

src/CrossMappings/ccm.jl
=> Rename theiler window parameter and simplify loop

docs/Project.toml, docs/src/s_measure.md, src/SMeasure/smeasure.jl
The docs are [here](https://juliadynamics.github.io/CausalityTools.jl/previews/PR151/).
- Notation fixes (more in line with original paper)
- Clearer code
- Documentation improvements (added docstrings and clarified what is returned)
=> Unneccessary imports

Project.toml, docs/src/TransferEntropy.md
New feature, so increment minor version.
The docs are [here](https://juliadynamics.github.io/CausalityTools.jl/previews/PR156/).
=> Add BBNUE methods to docs.

docs/src/api/api_condmutualinfo.md, docs/src/examples.md, docs/src/examples/examples_conditional_mutual_information.md, docs/src/examples/examples_independence.md, docs/src/examples/examples_mi.md, src/independence_tests/independence.jl, src/independence_tests/surrogate/SurrogateTest.jl, src/independence_tests/surrogate/condmutualinfo.jl, src/independence_tests/surrogate/mutualinfo.jl, src/independence_tests/surrogate/transferentropy.jl, src/methods/infomeasures/mutualinfo/estimators/GaussianMI.jl, src/methods/infomeasures/mutualinfo/mutualinfo.jl, test/independence/SurrogateTest/ConditionalMutualInformation.jl, test/independence/SurrogateTest/MutualInformation.jl, test/methods/infomeasures/conditional_mutualinfo/CMIShannon.jl, test/methods/infomeasures/mutualinfo/estimators.jl
- Fixes #205.
- Fixes #206.
- Fixes #207.
- Fixes #208. 
- Fixes #170
=> Fix various issues

src/independence_tests/local_permutation/LocalPermutationTest.jl, test/independence/LocalPermutation.jl, test/independence/SurrogateTest/ConditionalMutualInformation.jl
=> Add list of compatible measures to LocalPermutationTest

docs/src/measures.md, src/example_systems/discrete/Logistic2Unidir.jl, src/independence_tests/surrogate/SurrogateTest.jl, src/methods/infomeasures/transferentropy/TERenyiJizba.jl, src/methods/infomeasures/transferentropy/TEShannon.jl, src/methods/infomeasures/transferentropy/estimators/Lindner.jl, src/methods/infomeasures/transferentropy/transferentropy.jl, test/independence/SurrogateTest/ConditionalMutualInformation.jl, test/independence/SurrogateTest/HMeasure.jl, test/independence/SurrogateTest/LMeasure.jl, test/independence/SurrogateTest/MMeasure.jl, test/independence/SurrogateTest/MutualInformation.jl, test/independence/SurrogateTest/SMeasure.jl, test/independence/SurrogateTest/SurrogateTest.jl, test/independence/SurrogateTest/TransferEntropyConditional.jl, test/independence/SurrogateTest/TransferEntropyPairwise.jl, test/independence/SurrogateTest/crossmappings.jl
=> Estimator tables for `transferentropy`, `TEShannon`, `TERenyiJizba`

docs/src/independence.md, src/independence_tests/independence.jl, src/independence_tests/local_permutation/LocalPermutationTest.jl, src/independence_tests/local_permutation/transferentropy.jl, src/independence_tests/parametric/JointDistanceDistributionTest.jl, src/independence_tests/surrogate/SurrogateTest.jl, src/independence_tests/surrogate/contingency.jl, src/independence_tests/surrogate/crossmapping.jl, src/independence_tests/surrogate/hlms_measure.jl, src/independence_tests/surrogate/transferentropy.jl
- Fixes #246
- Cleans up a bit of code redundancy
=> Document test result types

docs/src/causal_graphs.md, src/causal_graphs/causal_graphs.jl, src/causal_graphs/oce/OCE.jl, src/causal_graphs/pc_mci/PCMCI.jl, src/causal_graphs/pc_mci/parent_selection.jl, src/causal_graphs/pc_pa/PCPA.jl, src/causal_graphs/pc_robust/PCRobust.jl, src/causal_graphs/pc_robust/cpdag.jl, src/causal_graphs/pc_robust/skeleton.jl, src/causal_graphs/pc_robust/skeleton_directed.jl, src/core.jl, src/independence_tests/correlation/correlation.jl, src/independence_tests/independence.jl, src/independence_tests/local_permutation/LocalPermutationTest.jl, src/independence_tests/parametric/JointDistanceDistributionTest.jl, src/independence_tests/parametric/PATest.jl, src/independence_tests/parametric/PredictiveAsymmetryTest.jl, src/independence_tests/surrogate/SurrogateTest.jl, src/methods/infomeasures/predictive_asymmetry/PA.jl, src/methods/infomeasures/predictive_asymmetry/embeddings.jl, src/methods/infomeasures/transferentropy/transferentropy.jl, test/independence/PATest.jl
- Introduce optimal causation entropy
- Don't make the PC-type algorithms public yet. There are some quirks to figure out first.
=> WIP: Graph algorithm improvements

src/causal_graphs/api.jl, src/causal_graphs/oce/OCE.jl
- Remove some forgotten `@show` statements
- Clearer docs.
- `GraphAlgorithm` list correct concrete implementation
=> Graphs cleanup

.github/workflows/documentation_preview_cleanup.yml
=> Add workflow for cleaning documentation PR previews

docs/src/causal_graphs.md, src/causal_graphs/causal_graphs.jl, src/causal_graphs/oce/OCE.jl, src/causal_graphs/printing.jl, test/causal_graphs/oce.jl
=> Better oce printing
